[package]
name = "rusb_async"
version = "0.3.5"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
bytes = "1.9.0"
rusb = { git = "https://github.com/three014/rusb.git", version = "0.9.4" }
tokio = { version = "1.43.0", default-features = false, features = ["rt", "sync", "macros"] }
tokio-util = { version = "0.7.13", default-features = false }
zerocopy = { version = "0.8.14", optional = true }
zerocopy-derive = { version = "0.8.14", optional = true }

[features]
zerocopy = ["dep:zerocopy", "dep:zerocopy-derive"]

[dev-dependencies]
tokio = { version = "1.43.0", default-features = false, features = ["rt-multi-thread", "time"] }
